package com.tweetapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Tweet")
public class Tweet implements Serializable {

    @DynamoDBHashKey(attributeName = "tweetID")
    @DynamoDBAutoGeneratedKey
    private String tweetID;

    @DynamoDBRangeKey(attributeName = "username")
    @DynamoDBIndexHashKey(attributeName = "username", globalSecondaryIndexName = "username-index")
    private String username;

    @DynamoDBAttribute(attributeName = "message")
    private String message;

    @DynamoDBAttribute(attributeName = "creationTime")
    private String creationTime;

    @DynamoDBAttribute(attributeName = "comments")
    private List<Comment> comments;

    @DynamoDBAttribute(attributeName = "likeCount")
    private int likeCount;
}
